export const COUNT_CONTRACT_ADDRESS = process.env.REACT_APP_TEST_COUNT_CONTRACT_ADDRESS;

export const NFT_CONTRACT_ADDRESS = process.env.REACT_APP_TEST_NFT_CONTRACT_ADDRESS;

export const MARKET_CONTRACT_ADDRESS = process.env.REACT_APP_TEST_MARKET_CONTRACT_ADDRESS;

export const ACCESS_KEY_ID = process.env.REACT_APP_TEST_ACCESS_KEY_ID;
export const SECRET_ACCESS_KEY = process.env.REACT_APP_TEST_SECRET_ACCESS_KEY;
export const CHAIN_ID = `1001` //1001: Baobab(TestNet), 8217: MainNet